#!/bin/sh
#
# Install files into the user's home directory.

[ -f $HOME/.bash_profile ] \
    && mv $HOME/.bash_profile{,.bak}
[ -f $HOME/.bashrc ] \
    && mv $HOME/.bashrc{,.bak}
[ -f $HOME/.bash_logout ] \
    && mv $HOME/.bash_logout{,.bak}

cp bash_profile $HOME/.bash_profile
cp bashrc $HOME/.bashrc
cp bash_logout $HOME/.bash_logout

mkdir -p $HOME/var
rsync -a --itemize-changes bin etc lib share var $HOME
